
class Keys:
    BINANCE_API_KEY = "SMQP7OPB5nO1yc1n2floYAjFc9ZZt4M1bt34aGgCA6IaDb2GFpx8GsDbBEnZ3aw5"
    BINANCE_SECRET_KEY = "WBG1DPCiJOcR6nwuZD78vchRcH26PxeIOs88ig4FWLajGX1N9DItwEPCNT3N0fdu"

    COINGECKO_API_KEY = ''
    COINGECKO_SECRET_KEY = ''
    
    NOBITEX_API_KEY = ''
    NOBITEX_SECRET_KEY = ''

    BITMEX_API_KEY = ''
    BITMEX_SECRET_KEY = ''
    
    HUOBI_API_KEY = ''
    HUOBI_SECRET_KEY = ''